
const fields=document.getElementById('variantFields'),list=document.getElementById('variantList');
const addForm=document.querySelector('form.admin-card');
addForm.addEventListener('submit',()=>{
  list.querySelectorAll('.variant-row').forEach((row,index)=>{
    const file=row.querySelector('input[type="file"][name^="variant_image"]');
    if(file)file.name=`variant_image[${index}]`;
  });
});
const singleOptions=<?= json_encode($availableSingles, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
function bindVariantImage(row){const file=row.querySelector('input[type="file"][name="variant_image[]"]');const img=row.querySelector('.variant-photo');if(!file||!img)return;file.onchange=()=>{const f=file.files[0];if(f)img.src=URL.createObjectURL(f);};}
function addVariant(product=null){const row=document.createElement('div');row.className='variant-row'+(product?' variant-existing':'');row.innerHTML=product?`<input name="variant_name[]" placeholder="åˆ†ç±»åç§°" required value="${product.name}"><input type="hidden" name="source_product_id[]" value="${product.id}"><input type="hidden" name="variant_sku[]" value=""><input type="hidden" name="variant_price[]" value=""><input type="hidden" name="variant_stock[]" value=""><input type="file" name="variant_image[]" hidden><div><strong>${product.sku}</strong><br><span>RM ${product.price} Â· åº“å­˜ ${product.stock}</span></div><button type="button" class="remove-variant">åˆ é™¤</button>`:`<input name="variant_name[]" placeholder="åˆ†ç±»åç§°" required><input type="hidden" name="source_product_id[]" value=""><input name="variant_sku[]" placeholder="SKU" required><input type="number" step=".01" min="0" name="variant_price[]" placeholder="ä»·æ ¼ RM" required><input type="number" min="0" name="variant_stock[]" placeholder="åº“å­˜" required><img class="variant-photo" src="/yummy-diary/images/soldout.png">
<input type="file" name="variant_image[]" accept="image/jpeg,image/png,image/gif,image/webp"><button type="button" class="remove-variant">åˆ é™¤</button>`;row.querySelector('.remove-variant').onclick=()=>row.remove();bindVariantImage(row);list.appendChild(row)}
document.getElementById('addVariant').onclick=()=>addVariant();
const picker=document.getElementById('productPicker');document.getElementById('useExisting').onclick=()=>picker.classList.add('show');picker.querySelector('.picker-close').onclick=()=>picker.classList.remove('show');picker.addEventListener('click',e=>{if(e.target===picker)picker.classList.remove('show')});picker.querySelectorAll('.picker-product').forEach(card=>card.onclick=()=>{addVariant();const row=list.lastElementChild;row.querySelector('[name="variant_name[]"]').value=card.dataset.name;row.querySelector('[name="source_product_id[]"]').value=card.dataset.id;row.querySelector('[name="variant_sku[]"]').value=card.dataset.sku;row.querySelector('[name="variant_price[]"]').value=card.dataset.price;row.querySelector('[name="variant_stock[]"]').value=card.dataset.stock;row.querySelector('.variant-photo').src=card.querySelector('img').src;picker.classList.remove('show')});pickerSearch.oninput=e=>{const q=e.target.value.toLowerCase();picker.querySelectorAll('.picker-product').forEach(card=>card.hidden=!card.dataset.search.includes(q))};
document.querySelectorAll('[name=product_type]').forEach(r=>r.onchange=()=>{const grouped=r.value==='grouped'&&r.checked;fields.classList.toggle('show',grouped);document.querySelectorAll('.single-only').forEach(el=>el.style.display=grouped?'none':'flex');[sku,price,stock].forEach(el=>el.required=!grouped);if(grouped&&!list.children.length)addVariant()});
['sku','name','price','stock'].forEach(id=>document.getElementById(id).oninput=()=>{previewName.textContent=name.value||'å•†å“åç§°';previewSku.textContent='SKUï¼š'+(sku.value||'-');previewStock.textContent='åº“å­˜ï¼š'+(stock.value||0);previewPrice.textContent='RM '+Number(price.value||0).toFixed(2)});
image.onchange=()=>{const f=image.files[0];if(f)previewImage.src=URL.createObjectURL(f)};

